// apps/web/src/components/command-palette.tsx
"use client"

import { useState, useEffect } from "react"
import { Command } from "cmdk"

interface CommandItem {
  id: string
  label: string
  description?: string
  group: "Files" | "Clusters" | "Actions"
  onSelect: () => void
}

interface CommandPaletteProps {
  open: boolean
  onClose: () => void
  items: CommandItem[]
}

export function CommandPalette({ open, onClose, items }: CommandPaletteProps) {
  const [search, setSearch] = useState("")

  useEffect(() => {
    if (!open) setSearch("")
  }, [open])

  if (!open) return null

  const groups = ["Files", "Clusters", "Actions"] as const

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center pt-16 sm:pt-24 px-4"
      role="dialog"
      aria-modal="true"
      aria-label="Command palette"
    >
      <div className="absolute inset-0 bg-background/60 backdrop-blur-sm animate-fade-in" onClick={onClose} />
      <div className="relative w-full max-w-lg bg-background border border-border rounded-xl shadow-2xl overflow-hidden animate-slide-in-top">
        <Command>
          <div className="flex items-center border-b border-border px-3">
            <span className="text-muted-foreground mr-2 text-sm">⌘</span>
            <Command.Input
              value={search}
              onValueChange={setSearch}
              placeholder="Search files, clusters, actions..."
              className="flex-1 py-3 text-sm bg-transparent outline-none placeholder:text-muted-foreground"
              aria-label="Search command palette"
            />
            <kbd className="text-xs text-muted-foreground border border-border rounded px-1">Esc</kbd>
          </div>

          <Command.List className="max-h-72 overflow-y-auto p-2">
            <Command.Empty className="py-6 text-center text-sm text-muted-foreground">
              {search ? `No files match "${search}". Try a shorter search.` : "No results found."}
            </Command.Empty>

            {groups.map(group => {
              const groupItems = items.filter(i => i.group === group)
              if (groupItems.length === 0) return null
              return (
                <Command.Group key={group} heading={group} className="[&_[cmdk-group-heading]]:text-[10px] [&_[cmdk-group-heading]]:text-muted-foreground [&_[cmdk-group-heading]]:uppercase [&_[cmdk-group-heading]]:tracking-wide [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1">
                  {groupItems.map(item => (
                    <Command.Item
                      key={item.id}
                      value={`${item.label} ${item.description ?? ""}`}
                      onSelect={() => { item.onSelect(); onClose() }}
                      className="flex items-center gap-2 px-2 py-1.5 rounded text-sm cursor-pointer data-[selected=true]:bg-muted aria-selected:bg-muted"
                    >
                      <span className="flex-1 truncate">{item.label}</span>
                      {item.description && (
                        <span className="text-xs text-muted-foreground truncate max-w-32">{item.description}</span>
                      )}
                    </Command.Item>
                  ))}
                </Command.Group>
              )
            })}
          </Command.List>
        </Command>
      </div>
    </div>
  )
}

// apps/web-solid/src/components/CommandPalette.tsx
import { createSignal, createMemo, For, Show, createEffect, onCleanup } from 'solid-js'
import type { PRFile } from '@/lib/github'
import type { RankedFile, Cluster } from '@/lib/ml'
import { ScoreBadge } from './ScoreBadge'
import { Portal } from 'solid-js/web'

interface Props {
  open: boolean
  onClose: () => void
  files: PRFile[]
  rankedFiles: RankedFile[]
  clusters: Cluster[]
  onSelectFile: (filename: string) => void
  onSelectCluster: (id: string | null) => void
}

export function CommandPalette(props: Props) {
  const [query, setQuery] = createSignal('')

  const rankMap = createMemo(() =>
    new Map(props.rankedFiles.map(r => [r.filename, r]))
  )

  const filteredFiles = createMemo(() => {
    const q = query().toLowerCase()
    if (!q) return props.files.slice(0, 10)
    return props.files.filter(f => f.filename.toLowerCase().includes(q)).slice(0, 10)
  })

  const filteredClusters = createMemo(() => {
    const q = query().toLowerCase()
    if (!q) return props.clusters
    return props.clusters.filter(c => c.label.toLowerCase().includes(q))
  })

  createEffect(() => {
    if (!props.open) return
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') props.onClose()
    }
    window.addEventListener('keydown', handler)
    onCleanup(() => window.removeEventListener('keydown', handler))
  })

  return (
    <Show when={props.open}>
      <Portal>
        <div
          class="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-start justify-center pt-24"
          onClick={props.onClose}
        >
          <div
            class="w-full max-w-xl bg-slate-800 rounded-xl border border-slate-600 shadow-2xl overflow-hidden"
            onClick={e => e.stopPropagation()}
          >
            <div class="flex items-center gap-3 p-3 border-b border-slate-700">
              <svg class="w-4 h-4 text-slate-400 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
              <input
                type="text"
                class="flex-1 bg-transparent text-slate-200 text-sm placeholder-slate-500 outline-none"
                placeholder="Search files, clusters..."
                value={query()}
                onInput={e => setQuery(e.currentTarget.value)}
                autofocus
              />
              <span class="text-xs text-slate-500 shrink-0">ESC to close</span>
            </div>

            <div class="max-h-80 overflow-y-auto p-1">
              <Show when={filteredClusters().length > 0}>
                <div class="px-3 py-1 text-xs text-slate-500 uppercase tracking-wider">Clusters</div>
                <For each={filteredClusters()}>
                  {cluster => (
                    <button
                      class="w-full flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-slate-700 transition-colors text-left"
                      onClick={() => { props.onSelectCluster(cluster.id); props.onClose() }}
                    >
                      <div class="w-2 h-2 rounded-full shrink-0" style={{ background: cluster.color }} />
                      <span class="text-sm text-slate-200">{cluster.label}</span>
                      <span class="ml-auto text-xs text-slate-500">{cluster.files.length} files</span>
                    </button>
                  )}
                </For>
              </Show>

              <Show when={filteredFiles().length > 0}>
                <div class="px-3 py-1 text-xs text-slate-500 uppercase tracking-wider mt-1">Files</div>
                <For each={filteredFiles()}>
                  {file => {
                    const rank = () => rankMap().get(file.filename)
                    return (
                      <button
                        class="w-full flex items-center gap-3 px-3 py-2 rounded-lg hover:bg-slate-700 transition-colors text-left"
                        onClick={() => { props.onSelectFile(file.filename); props.onClose() }}
                      >
                        <span class="text-sm text-slate-300 truncate flex-1 font-mono">{file.filename}</span>
                        <Show when={rank()}>
                          <ScoreBadge label={rank()!.label} />
                        </Show>
                      </button>
                    )
                  }}
                </For>
              </Show>

              <Show when={filteredFiles().length === 0 && filteredClusters().length === 0}>
                <div class="px-3 py-6 text-center text-slate-500 text-sm">
                  No files match "{query()}". Try a shorter search.
                </div>
              </Show>
            </div>
          </div>
        </div>
      </Portal>
    </Show>
  )
}
