// apps/web/src/components/error-boundary.tsx
"use client"

import React from "react"
import { useRouter } from "next/navigation"

interface ErrorBoundaryState {
  hasError: boolean
  error: Error | null
}

interface ErrorBoundaryProps {
  children: React.ReactNode
}

class ErrorBoundaryClass extends React.Component<
  ErrorBoundaryProps & { onReset: () => void },
  ErrorBoundaryState
> {
  constructor(props: ErrorBoundaryProps & { onReset: () => void }) {
    super(props)
    this.state = { hasError: false, error: null }
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error }
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="flex flex-col items-center justify-center min-h-[300px] p-8 text-center">
          <h2 className="text-xl font-semibold mb-2">Something went wrong</h2>
          <p className="text-sm text-muted-foreground mb-4">
            {this.state.error?.message ?? "An unexpected error occurred"}
          </p>
          <button
            className="px-4 py-2 rounded bg-primary text-primary-foreground text-sm hover:opacity-90 transition-opacity"
            onClick={() => {
              this.setState({ hasError: false, error: null })
              this.props.onReset()
            }}
          >
            Try again
          </button>
        </div>
      )
    }
    return this.props.children
  }
}

export function ErrorBoundary({ children }: ErrorBoundaryProps) {
  const router = useRouter()
  return (
    <ErrorBoundaryClass onReset={() => router.refresh()}>
      {children}
    </ErrorBoundaryClass>
  )
}

// apps/web-solid/src/components/ErrorBoundary.tsx
import { ErrorBoundary as SolidErrorBoundary } from 'solid-js'
import type { ParentProps } from 'solid-js'

interface Props extends ParentProps {
  fallback?: (err: Error, reset: () => void) => any
}

export function ErrorBoundary(props: Props) {
  return (
    <SolidErrorBoundary fallback={(err, reset) => (
      props.fallback?.(err, reset) ?? (
        <div class="flex flex-col items-center justify-center p-8 gap-4">
          <p class="text-[var(--critical)] text-sm">Something went wrong</p>
          <button
            onClick={() => window.location.reload()}
            class="text-xs px-3 py-1.5 bg-[var(--bg-elevated)] border border-[var(--border)] text-[var(--text-primary)] rounded hover:border-[var(--accent)] transition-colors"
          >
            Try Again
          </button>
        </div>
      )
    )}>
      {props.children}
    </SolidErrorBoundary>
  )
}
