// apps/web/src/components/RateLimitBar.tsx
"use client"

import useSWR from "swr"

interface RateLimitData {
  remaining: number
  limit: number
  reset: number | null
}

const fetcher = (url: string) => fetch(url).then(r => r.json())

export function useRateLimitExhausted(): boolean {
  const { data } = useSWR<RateLimitData>("/api/github/ratelimit", fetcher, { refreshInterval: 30000 })
  return data?.remaining === 0
}

export function RateLimitBar() {
  const { data } = useSWR<RateLimitData>("/api/github/ratelimit", fetcher, { refreshInterval: 30000 })

  if (!data) return null

  const { remaining, limit, reset } = data

  if (remaining === 0) {
    const resetTime = reset ? new Date(reset * 1000).toLocaleTimeString() : "soon"
    return (
      <span className="text-xs px-2 py-0.5 rounded-full bg-red-500/20 text-red-400 border border-red-500/40">
        Rate limited · resets {resetTime}
      </span>
    )
  }

  if (remaining < 100) {
    return (
      <span className="text-xs px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-400 border border-amber-500/40">
        GitHub API: {remaining}/{limit}
      </span>
    )
  }

  return (
    <span className="text-xs text-muted-foreground">
      GitHub API: {remaining}/{limit}
    </span>
  )
}

// apps/web-solid/src/components/RateLimitBar.tsx
import { createSignal, onCleanup, Show } from 'solid-js'

interface RateLimit { remaining: number; limit: number; reset: number | null }

const [rateLimit, setRateLimit] = createSignal<RateLimit>({ remaining: 5000, limit: 5000, reset: null })

export function useRateLimitExhausted() {
  return () => rateLimit().remaining === 0
}

export function RateLimitBar() {
  async function fetchRateLimit() {
    const res = await fetch('/api/github/rate_limit')
    if (!res.ok) return
    const data = await res.json() as { rate: { remaining: number; limit: number; reset: number } }
    setRateLimit({ remaining: data.rate.remaining, limit: data.rate.limit, reset: data.rate.reset })
  }

  fetchRateLimit()
  const interval = setInterval(fetchRateLimit, 30_000)
  onCleanup(() => clearInterval(interval))

  const isWarning = () => rateLimit().remaining < 100 && rateLimit().remaining > 0
  const isExhausted = () => rateLimit().remaining === 0

  return (
    <Show when={rateLimit().remaining < 500}>
      <span class={`text-xs px-2 py-1 rounded ${
        isExhausted() ? 'bg-red-900/50 text-red-300' :
        isWarning() ? 'bg-yellow-900/50 text-yellow-300' :
        'text-slate-400'
      }`}>
        {isExhausted()
          ? `Rate limited · resets ${new Date((rateLimit().reset ?? 0) * 1000).toLocaleTimeString()}`
          : `API: ${rateLimit().remaining}/${rateLimit().limit}`
        }
      </span>
    </Show>
  )
}
