// apps/web-solid/src/components/pr-review/DiffViewer.tsx
import { createSignal, For, Show, createMemo } from 'solid-js'
import type { PRFile } from '@/lib/github'
import type { RankedFile } from '@/lib/ml'
import { ScoreBadge } from '@/components/ScoreBadge'

interface DiffLine {
  type: 'add' | 'remove' | 'context' | 'hunk'
  content: string
  oldLine: number | null
  newLine: number | null
}

function parsePatch(patch: string): DiffLine[] {
  const lines = patch.split('\n')
  const result: DiffLine[] = []
  let oldLine = 0, newLine = 0

  for (const line of lines) {
    if (line.startsWith('@@')) {
      const match = line.match(/@@ -(\d+)(?:,\d+)? \+(\d+)/)
      if (match) { oldLine = parseInt(match[1]); newLine = parseInt(match[2]) }
      result.push({ type: 'hunk', content: line, oldLine: null, newLine: null })
    } else if (line.startsWith('+')) {
      result.push({ type: 'add', content: line.slice(1), oldLine: null, newLine: newLine++ })
    } else if (line.startsWith('-')) {
      result.push({ type: 'remove', content: line.slice(1), oldLine: oldLine++, newLine: null })
    } else {
      result.push({ type: 'context', content: line.slice(1), oldLine: oldLine++, newLine: newLine++ })
    }
  }
  return result
}

interface Props {
  file: PRFile | null
  rank: RankedFile | null
  prId: string
  owner: string
  repo: string
  commentOpen: boolean
  onCommentClose: () => void
}

export function DiffViewer(props: Props) {
  const [activeCommentLine, setActiveCommentLine] = createSignal<number | null>(null)
  const [commentText, setCommentText] = createSignal('')
  const [comments, setComments] = createSignal<Array<{ line: number; body: string; author: string }>>([])
  const [failedLines, setFailedLines] = createSignal(new Set<number>())

  const lines = createMemo(() => {
    if (!props.file?.patch) return []
    return parsePatch(props.file.patch)
  })

  async function submitComment(line: number) {
    const body = commentText()
    if (!body.trim()) return

    setComments(prev => [...prev, { line, body, author: 'you' }])
    setCommentText('')
    setActiveCommentLine(null)

    let attempts = 0
    const delays = [1000, 2000, 4000]
    while (attempts < 3) {
      try {
        const res = await fetch('/api/github/comment', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            owner: props.owner, repo: props.repo,
            pr_number: props.prId, body, path: props.file?.filename, line,
          }),
        })
        if (res.ok) return
      } catch {}
      attempts++
      if (attempts < 3) await new Promise(r => setTimeout(r, delays[attempts - 1]))
    }
    setFailedLines(prev => new Set([...prev, line]))
  }

  return (
    <Show when={props.file} fallback={
      <div class="flex items-center justify-center h-full text-[var(--text-muted)]">
        <p class="text-sm">Select a file to review</p>
      </div>
    }>
      <div class="bg-[var(--bg-surface)] border border-[var(--border)] rounded-lg overflow-hidden m-4">
        {/* File header */}
        <div class="px-4 py-2.5 border-b border-[var(--border)] bg-[var(--bg-elevated)] flex items-center gap-3">
          <span class="mono text-xs text-[var(--text-primary)] font-medium truncate flex-1">{props.file?.filename}</span>
          <Show when={props.rank}>
            <ScoreBadge label={props.rank!.label} />
          </Show>
          <span class="text-xs shrink-0">
            <span class="text-[var(--success)]">+{props.file?.additions}</span>
            {' '}
            <span class="text-[var(--critical)]">-{props.file?.deletions}</span>
          </span>
        </div>

        {/* Diff lines */}
        <Show when={props.file?.patch} fallback={
          <div class="p-4 text-[var(--text-muted)] text-xs mono italic">
            {props.file?.status === 'binary' ? 'Binary file' : 'No diff available'}
          </div>
        }>
          <div class="mono text-xs leading-5">
            <table class="w-full border-collapse">
              <tbody>
                <For each={lines()}>
                  {(line, i) => (
                    <>
                      <tr
                        class={`group cursor-pointer ${
                          line.type === 'add' ? 'bg-[var(--add)]' :
                          line.type === 'remove' ? 'bg-[var(--remove)]' :
                          line.type === 'hunk' ? 'bg-[var(--accent-subtle)]' :
                          'hover:bg-[var(--bg-elevated)]'
                        }`}
                        onClick={() => line.type !== 'hunk' && setActiveCommentLine(
                          activeCommentLine() === i() ? null : i()
                        )}
                      >
                        <td class="w-10 px-2 py-0.5 text-[var(--text-muted)] select-none text-right border-r border-[var(--border-subtle)]">
                          {line.oldLine ?? ''}
                        </td>
                        <td class="w-10 px-2 py-0.5 text-[var(--text-muted)] select-none text-right border-r border-[var(--border-subtle)]">
                          {line.newLine ?? ''}
                        </td>
                        <td class={`px-3 py-0.5 whitespace-pre ${
                          line.type === 'add' ? 'text-[var(--success)]' :
                          line.type === 'remove' ? 'text-[var(--critical)]' :
                          line.type === 'hunk' ? 'text-[var(--accent)]' :
                          'text-[var(--text-secondary)]'
                        }`}>
                          {line.type === 'add' ? '+' : line.type === 'remove' ? '-' : line.type === 'hunk' ? '' : ' '}
                          {line.content}
                        </td>
                        <td class="w-6 px-1 opacity-0 group-hover:opacity-100">
                          <button class="text-[var(--text-muted)] hover:text-[var(--accent)] transition-colors text-xs">+</button>
                        </td>
                      </tr>

                      {/* Inline comments */}
                      <For each={comments().filter(c => c.line === i())}>
                        {comment => (
                          <tr>
                            <td colspan={4} class="px-4 py-2 bg-[var(--accent-subtle)] border-l-2 border-[var(--accent)]">
                              <div class="flex items-start gap-2">
                                <span class="text-[var(--accent)] text-xs font-medium">{comment.author}</span>
                                <span class="text-[var(--text-secondary)] text-xs">{comment.body}</span>
                                <Show when={failedLines().has(comment.line)}>
                                  <span class="text-[var(--critical)] text-xs ml-auto">
                                    Failed to post ·{' '}
                                    <button
                                      class="underline"
                                      onClick={() => submitComment(comment.line)}
                                    >Retry</button>
                                  </span>
                                </Show>
                              </div>
                            </td>
                          </tr>
                        )}
                      </For>

                      {/* Comment input */}
                      <Show when={activeCommentLine() === i()}>
                        <tr>
                          <td colspan={4} class="px-4 py-3 bg-[var(--bg-elevated)]">
                            <textarea
                              class="w-full bg-[var(--bg-surface)] text-[var(--text-primary)] text-xs p-2 rounded border border-[var(--border)] resize-none focus:outline-none focus:border-[var(--accent)] transition-colors mono"
                              rows={3}
                              placeholder="Add a review comment..."
                              value={commentText()}
                              onInput={e => setCommentText(e.currentTarget.value)}
                              autofocus
                            />
                            <div class="flex gap-2 mt-2">
                              <button
                                class="text-xs bg-[var(--accent)] hover:bg-[var(--accent)]/80 text-white px-3 py-1 rounded transition-colors"
                                onClick={() => submitComment(i())}
                              >Comment</button>
                              <button
                                class="text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] px-3 py-1 rounded transition-colors"
                                onClick={() => setActiveCommentLine(null)}
                              >Cancel</button>
                            </div>
                          </td>
                        </tr>
                      </Show>
                    </>
                  )}
                </For>
              </tbody>
            </table>
          </div>
        </Show>
      </div>
    </Show>
  )
}

// apps/web/src/components/pr-review/diff-viewer.tsx
"use client"

import { useMemo, useState } from "react"
import React from "react"
import { useComments } from "@/hooks/use-comments"
import { CommentThread } from "@/components/comment-thread"

interface DiffLine {
  type: "add" | "remove" | "context" | "hunk-header"
  content: string
  oldLineNum?: number
  newLineNum?: number
}

interface DiffViewerProps {
  patch: string
  filename: string
  viewMode: "unified" | "split"
  prId?: string
  currentUser?: { name: string; image?: string }
  activeCommentLine?: number | null
  onCommentClose?: () => void
  isLoading?: boolean
}

function parsePatch(patch: string): DiffLine[] {
  if (!patch) return []
  const lines: DiffLine[] = []
  let oldLine = 0
  let newLine = 0

  for (const line of patch.split("\n")) {
    if (line.startsWith("@@")) {
      const match = line.match(/@@ -(\d+)(?:,\d+)? \+(\d+)/)
      if (match) {
        oldLine = parseInt(match[1], 10)
        newLine = parseInt(match[2], 10)
      }
      lines.push({ type: "hunk-header", content: line })
    } else if (line.startsWith("+") && !line.startsWith("+++")) {
      lines.push({ type: "add", content: line.slice(1), newLineNum: newLine++ })
    } else if (line.startsWith("-") && !line.startsWith("---")) {
      lines.push({ type: "remove", content: line.slice(1), oldLineNum: oldLine++ })
    } else if (line.startsWith(" ")) {
      lines.push({ type: "context", content: line.slice(1), oldLineNum: oldLine++, newLineNum: newLine++ })
    }
  }
  return lines
}

function LineNumber({ n }: { n?: number }) {
  return (
    <td className="select-none w-12 pr-3 text-right text-xs text-muted-foreground/60 font-mono border-r border-border/40">
      {n ?? ""}
    </td>
  )
}

export function DiffViewer({ patch, filename, viewMode, prId, currentUser, isLoading }: DiffViewerProps) {
  const lines = useMemo(() => parsePatch(patch), [patch])
  const [activeRow, setActiveRow] = useState<number | null>(null)
  const [failedLines, setFailedLines] = useState<Set<number>>(new Set())
  const { comments, addComment, resolveComment, deleteComment } = useComments(prId ?? "", filename)

  const handleAddComment = (lineNumber: number, body: string) => {
    addComment(lineNumber, body, currentUser?.name ?? "anonymous", currentUser?.image ?? "")

    if (prId) {
      // Best-effort GitHub API comment — fire and forget
      fetch("/api/github/comment", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ path: filename, line: lineNumber, body }),
      }).catch(() => {
        setFailedLines(prev => new Set(prev).add(lineNumber))
      })
    }
  }

  if (isLoading) {
    return (
      <div className="space-y-2 p-4">
        {Array.from({ length: 8 }).map((_, i) => (
          <div key={i} className="h-4 bg-muted animate-pulse rounded" />
        ))}
      </div>
    )
  }

  if (!patch || lines.length === 0) {
    return (
      <div className="text-center py-8 text-muted-foreground text-sm">
        No diff available for this file.
      </div>
    )
  }

  if (viewMode === "split") {
    const leftLines = lines.filter(l => l.type !== "add")
    const rightLines = lines.filter(l => l.type !== "remove")

    return (
      <div className="flex gap-0 overflow-x-auto font-mono text-xs">
        <div className="flex-1 min-w-0 border-r border-border">
          <table className="w-full border-collapse" role="table" aria-label="Removed lines">
            <tbody>
              {leftLines.map((line, i) => (
                <tr key={i} className={line.type === "remove" ? "bg-red-950/30" : line.type === "hunk-header" ? "bg-muted/50" : ""}>
                  <LineNumber n={line.oldLineNum} />
                  <td className="px-3 py-0.5 whitespace-pre overflow-hidden text-ellipsis max-w-0" style={{ width: "100%" }}>
                    <span className={line.type === "remove" ? "text-red-400" : "text-foreground"}>{line.content}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex-1 min-w-0">
          <table className="w-full border-collapse" role="table" aria-label="Added lines">
            <tbody>
              {rightLines.map((line, i) => (
                <tr key={i} className={line.type === "add" ? "bg-green-950/30" : line.type === "hunk-header" ? "bg-muted/50" : ""}>
                  <LineNumber n={line.newLineNum} />
                  <td className="px-3 py-0.5 whitespace-pre overflow-hidden text-ellipsis max-w-0" style={{ width: "100%" }}>
                    <span className={line.type === "add" ? "text-green-400" : "text-foreground"}>{line.content}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    )
  }

  // Unified view
  return (
    <div className="overflow-x-auto font-mono text-xs">
      <table className="w-full border-collapse" role="table" aria-label="Unified diff">
        <tbody>
          {lines.map((line, i) => {
            const rowClass =
              line.type === "add" ? "bg-green-950/30" :
              line.type === "remove" ? "bg-red-950/30" :
              line.type === "hunk-header" ? "bg-muted/50" : ""
            const textClass =
              line.type === "add" ? "text-green-400" :
              line.type === "remove" ? "text-red-400" :
              line.type === "hunk-header" ? "text-blue-400" : "text-foreground"
            const gutter =
              line.type === "add" ? "+" :
              line.type === "remove" ? "-" :
              line.type === "hunk-header" ? "@" : " "
            const lineNum = line.newLineNum ?? line.oldLineNum
            const canComment = line.type !== "hunk-header" && lineNum !== undefined
            const lineComments = comments.filter(c => c.line_number === lineNum)

            return (
              <React.Fragment key={i}>
                <tr
                  className={`${rowClass} ${canComment ? "cursor-pointer hover:brightness-110" : ""}`}
                  role="row"
                  onClick={canComment ? () => setActiveRow(activeRow === i ? null : i) : undefined}
                >
                  <LineNumber n={line.oldLineNum} />
                  <LineNumber n={line.newLineNum} />
                  <td className="w-4 text-center text-muted-foreground/60 select-none">{gutter}</td>
                  <td className="px-3 py-0.5 whitespace-pre overflow-hidden text-ellipsis max-w-0" style={{ width: "100%" }} role="cell">
                    <span className={textClass}>{line.content}</span>
                    {lineComments.length > 0 && (
                      <span className="ml-2 text-[10px] text-primary/70">💬 {lineComments.length}</span>
                    )}
                    {lineNum !== undefined && failedLines.has(lineNum) && (
                      <span className="ml-2 text-[10px] text-destructive" title="GitHub comment failed">⚠</span>
                    )}
                  </td>
                </tr>
                {activeRow === i && canComment && lineNum !== undefined && (
                  <tr>
                    <td colSpan={4} className="px-4 py-2 bg-card">
                      <CommentThread
                        lineNumber={lineNum}
                        comments={comments}
                        onAddComment={handleAddComment}
                        onResolve={resolveComment}
                        onDelete={deleteComment}
                        currentUser={currentUser}
                      />
                    </td>
                  </tr>
                )}
              </React.Fragment>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}
