// apps/web-solid/src/components/pr-review/FileList.tsx
import { createMemo, For, Show } from 'solid-js'
import { createVirtualizer } from '@tanstack/solid-virtual'
import { ScoreBadge } from '@/components/ScoreBadge'
import type { PRFile } from '@/lib/github'
import type { RankedFile } from '@/lib/ml'

interface Props {
  files: PRFile[]
  rankedFiles: RankedFile[]
  selectedFile: string | null
  focusedFile: string | null
  selectedCluster: string | null
  clusterFileMap: Record<string, string>
  aiPriority: boolean
  onSelectFile: (filename: string) => void
}

export function FileList(props: Props) {
  let parentRef!: HTMLDivElement

  const sortedFiles = createMemo(() => {
    if (!props.aiPriority || props.rankedFiles.length === 0) return props.files
    const scoreMap = new Map(props.rankedFiles.map(r => [r.filename, r.final_score]))
    return [...props.files].sort((a, b) => (scoreMap.get(b.filename) ?? 0) - (scoreMap.get(a.filename) ?? 0))
  })

  const virtualizer = createVirtualizer({
    get count() { return sortedFiles().length },
    getScrollElement: () => parentRef,
    estimateSize: () => 52,
    overscan: 5,
  })

  const rankMap = createMemo(() =>
    new Map(props.rankedFiles.map(r => [r.filename, r]))
  )

  return (
    <div ref={parentRef} class="overflow-y-auto h-full">
      <div style={{ height: `${virtualizer.getTotalSize()}px`, position: 'relative' }}>
        <For each={virtualizer.getVirtualItems()}>
          {(virtualRow) => {
            const file = () => sortedFiles()[virtualRow.index]
            const rank = () => rankMap().get(file().filename)
            const isSelected = () => props.selectedFile === file().filename
            const clusterColor = () => props.clusterFileMap[file().filename]
            const shortFilename = () => {
              const parts = file().filename.split('/')
              return parts.length > 2 ? `.../${parts.slice(-2).join('/')}` : file().filename
            }

            return (
              <div
                style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  width: '100%',
                  height: `${virtualRow.size}px`,
                  transform: `translateY(${virtualRow.start}px)`,
                }}
              >
                <div
                  class={`px-3 py-2 cursor-pointer border-l-2 transition-all ${
                    isSelected() ? 'border-[var(--accent)] bg-[var(--bg-elevated)]' : 'border-transparent hover:bg-[var(--bg-elevated)]'
                  }`}
                  style={clusterColor() ? { 'border-left-color': clusterColor() } : {}}
                  onClick={() => props.onSelectFile(file().filename)}
                >
                  <div class="flex items-center justify-between gap-2">
                    <span class="mono text-xs text-[var(--text-primary)] truncate">{shortFilename()}</span>
                    <Show when={rank() && props.aiPriority}>
                      <ScoreBadge label={rank()!.label} />
                    </Show>
                  </div>
                  <div class="flex gap-2 mt-0.5 mono text-[10px]">
                    <span class="text-[var(--success)]">+{file().additions}</span>
                    <span class="text-[var(--critical)]">-{file().deletions}</span>
                  </div>
                </div>
              </div>
            )
          }}
        </For>
      </div>
    </div>
  )
}

// apps/web/src/components/pr-review/file-list.tsx
"use client"

import { useVirtualizer } from "@tanstack/react-virtual"
import { useRef, useState } from "react"
import { detectLanguage } from "@/lib/language"

export interface FileListItem {
  filename: string
  additions: number
  deletions: number
  patch?: string
  rank?: number
  finalScore?: number
  rerankerScore?: number
  retrievalScore?: number
  label?: string
  explanation?: string
  clusterId?: number
  clusterLabel?: string
}

interface FileListProps {
  files: FileListItem[]
  selectedFile: string | null
  onSelectFile: (filename: string) => void
  filterClusterId?: number | null
  focusedFile?: string | null
}

function LabelBadge({ label }: { label: string }) {
  const styles =
    label === "Critical" ? "bg-red-500/20 text-red-400 border-red-500/40" :
    label === "Important" ? "bg-yellow-500/20 text-yellow-400 border-yellow-500/40" :
    "bg-muted text-muted-foreground border-border"

  return (
    <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded border ${styles}`}>
      {label}
    </span>
  )
}

export function FileList({ files, selectedFile, onSelectFile, filterClusterId, focusedFile }: FileListProps) {
  const parentRef = useRef<HTMLDivElement>(null)
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set())

  const filteredFiles = filterClusterId != null
    ? files.filter(f => f.clusterId === filterClusterId)
    : files

  const virtualizer = useVirtualizer({
    count: filteredFiles.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 52,
    overscan: 5,
  })

  if (filteredFiles.length === 0) {
    return (
      <div className="flex items-center justify-center h-full text-muted-foreground text-sm">
        No files
      </div>
    )
  }

  return (
    <div ref={parentRef} className="h-full overflow-y-auto" role="list" aria-label="Changed files">
      <div style={{ height: `${virtualizer.getTotalSize()}px`, position: "relative" }}>
        {virtualizer.getVirtualItems().map((virtualItem) => {
          const file = filteredFiles[virtualItem.index]
          const isSelected = selectedFile === file.filename
          const isCollapsed = collapsed.has(file.filename)

          return (
            <div
              key={virtualItem.key}
              style={{ position: "absolute", top: 0, left: 0, width: "100%", transform: `translateY(${virtualItem.start}px)` }}
            >
              <button
                className={`w-full text-left px-3 py-2 text-xs hover:bg-muted/50 transition-colors flex items-center gap-2 ${isSelected ? "bg-muted border-l-2 border-primary" : "border-l-2 border-transparent"} ${file.filename === focusedFile ? "ring-2 ring-primary ring-offset-1" : ""}`}
                onClick={() => onSelectFile(file.filename)}
                tabIndex={0}
                aria-selected={isSelected}
                role="listitem"
              >
                {file.label != null && <LabelBadge label={file.label} />}
                <span className="flex-1 truncate font-mono text-[11px]">{file.filename}</span>
                <span className="flex items-center gap-1 shrink-0">
                  <span className="text-green-500 text-[10px]">+{file.additions}</span>
                  <span className="text-red-500 text-[10px]">-{file.deletions}</span>
                </span>
              </button>
            </div>
          )
        })}
      </div>
    </div>
  )
}
